(ns the-beer-list.types.beer-flavors)

;; Taken from https://1.bp.blogspot.com/-NYVymhX0Etg/UMzKgfXDdWI/AAAAAAAAAac/sH56SnEFKYQ/s1600/beer+tasting+wheel+wheel.png

(def flavors #{"Bitter"
               "Salty"

               "Sweet"
               "Oversweet"
               "Syrupy"
               "Primings"
               "Vanilla"
               "Jam-like"
               "Honey"

               "Acidic"
               "Sour"
               "Acetic"

               "Moldy"
               "Stale"
               "Musty"
               "Earthy"
               "Leathery"
               "Papery"
               "Yeasty"

               "Sulfury"
               "Cooked onion"
               "Cooked tomato"
               "Cooked sweet corn"
               "Cooked cabbage"
               "Dimethy sulfide"
               "Parsnip/Celery"
               "Shrimp-like"
               "Burnt rubber"
               "Autolysed"
               "Lightstruck"
               "Garlic"
               "Mercaptan"
               "Hydrogen Sulfide"
               "Meaty"
               "Striking match"

               "Fatty"
               "Mineral oil"
               "Vegetable oil"
               "Rancid"
               "Diacetyl"
               "Butyric"
               "Isovaleric"
               "Cheesy"
               "Caprylic"

               "Phenolic"
               "Isodoform"
               "Chlorophenol"
               "Carbolic"
               "Bakelite"
               "Tarry"

               "Smoky"
               "Burnt"
               "Roast barley"
               "Bread crust"
               "Caramel"
               "Licoric"
               "Molasses"
               "Worthy"
               "Malty"

               "Cereal"
               "Mealy"
               "Corn grits"
               "Husky"

               "Vegetal"
               "Straw-like"
               "Grassy"
               "Freshly cut grass"
               "Nutty"
               "Almond"
               "Beany"
               "Coconut"
               "Walnut"
               "Woody"
               "Piney"

               "Aromatic"
               "Fragrant"
               "Fruity"
               "Strawberry"
               "Raspberry"
               "Pear"
               "Melony"
               "Black currant"
               "Banana"
               "Apple"
               "Citrus"

               "Floral"
               "Estery"
               "Ethyl acetate"
               "Ethyl hexanoate"
               "Isoamyl acetate"

               "Solvent-like"
               "Laquer-like"
               "Can-liner"
               "Plastics"
               "Alcoholic"
               "Vinous"
               "Spicy"

               "Hoppy"
               "Hop oil"
               "Dry-hop"
               "Kettle-hop"

               "Perfumy"
               "Geraniol"
               "2-Phenylethanol"
               "Acetaldehyde"

               "Thick"
               "Satiating"
               "Characterless"
               "Watery"
               "Warming"
               "Piquant"

               "Bubbly"
               "Flat"

               "Powdery"
               "Puckering"
               "Tart"
               "Drying"

               "Metallic"
               "Mouthcoating"
               "Alkaline"})
