version: 2.1

docker:
  - image: 'cimg/openjdk:11.0-node'

jobs:
  build:
    steps:
      - checkout
      - restore_cache:
          key: 'v1-npm-{{ checksum "package-lock.json" }}'
      - run: npm install
      - save_cache:
          key: 'v1-npm-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
  deploy:
    steps:
      - run: npm run release
      - run: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              master
