version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:11.0.16-node'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-npm-{{ checksum "package-lock.json" }}'
      - run: npm ci
      - save_cache:
          key: 'v1-npm-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: 'cimg/openjdk:11.0-node'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-npm-{{ checksum "package-lock.json" }}'
      - run: npm run release
      - run: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
