version: 2.1

orbs:
  node: circleci/node@4.7 
  openjdk-install: cloudesire/openjdk-install@1.2.3

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  install-deps:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - openjdk-install/openjdk:
          version: 11
          cache_version: 1

workflows:
  deploy:
    jobs:
      - install-deps
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
