version: 2.1

jobs:
  check_npm_version_15:
    docker:
      - image: 'cimg/openjdk:15.0-node'
    steps:
      - run: node -v
  check_npm_version_16:
    docker:
      - image: 'cimg/openjdk:16.0-node'
    steps:
      - run: node -v
  check_npm_version_17:
    docker:
      - image: 'cimg/openjdk:17.0-node'
    steps:
      - run: node -v

  build:
    docker:
      - image: 'cimg/openjdk:14.0-node'
    steps:
      - checkout
      - restore_cache:
          key: 'v4-npm-{{ checksum "package-lock.json" }}'
      - run: npm ci --legacy-peer-deps
      - save_cache:
          key: 'v4-npm-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: 'cimg/openjdk:14.0-node'
    steps:
      - checkout
      - restore_cache:
          key: 'v4-npm-{{ checksum "package-lock.json" }}'
      - run: npm run release
      - run: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  check_versions:
    jobs:
      - check_npm_version_15
      - check_npm_version_16
      - check_npm_version_17
  # build_and_deploy:
  #   jobs:
  #     - build
  #     - deploy:
  #         requires:
  #           - build
  #         filters:
  #           branches:
  #             only:
  #               - master
