version: 2.1

jobs:
  package-and-deploy:
    docker:
      - image: 'cimg/openjdk:11.0-node'
    steps:
      - checkout
      - run: npm install
      - run: npm release
          
workflows:
  deploy:
    jobs:
      - package-and-deploy
